### ISSUE TITLE
Volume calculation error

### ISSUE THREAD

**Issue by NinadBhat** [pyscal/atomRDF#81]
Creating a HCP Mg lattice with primitive=True and no repetitions shows a volume of "2993.63" (hasVolume field in turtle file). This is higher than expected as the cell lengths are  (3.21,3.21,5.25).

**Code to reproduce error:**

```python
kg = KnowledgeGraph()

struct_Mg = System.create.element.Mg(graph=kg, primitive=True)
kg.write("test_mg.ttl", format="ttl")
```

**Versions**
pyscal_rdf: 0.3.2

**Comment by srmnitc** [comment]
Thanks for reporting! This is a bug coming from pyscal3. The code uses an internal bigger cell for smaller ones, and it was reporting the volume for this bigger cell. It is fixed in https://github.com/pyscal/pyscal3/pull/37. Updating pyscal3 to 3.1.12 should fix this issue. [Tests](https://github.com/pyscal/pyscal3/blob/main/tests/test_system.py#L65) are also updated.

**Comment by NinadBhat** [comment]
Thanks for fixing @srmnitc .
